### ISSUE TITLE
Final Mission - Stuck at end of Encounter 1

### ISSUE THREAD

**Issue by Sylar1982** [DelphiDie/TheShadowRune#5]
on the red objective then Yes to the question "Are there no more ritual components...".

After the two mission dialogs, where i click Continue and Continue, nothing happens :(

I'll attach the save zip file.

Thanks for any help.

![immagine](https://user-images.githubusercontent.com/56688992/67020232-2d11a000-f0fe-11e9-8a0c-2c8659f72dcd.png)

![immagine](https://user-images.githubusercontent.com/56688992/67020381-69dd9700-f0fe-11e9-9e0e-3ea650d4aa70.png)

[save1.zip](https://github.com/DelphiDie/TheShadowRune/files/3739924/save1.zip)

**Comment by MrTantum** [comment]
Thanks for reporting this issue. 

This was a quite easy fix: The path to the next encounter was incorrect because of it was event1=/19_GU/**GUR**2/quest.ini instead of event1=/19_GU/**GU**2/quest.ini.

We'll try to update the campaign as soon as possible.

**Comment by DelphiDie** [comment]
Hello Sylar,

I tried to fix the savegame and will attach it here. I couldn't test this though, as there are a lot of variables  in the save, that refer to the system of the user. Please give it a try.


[save2.zip](https://github.com/DelphiDie/TheShadowRune/files/3746437/save2.zip)

**Comment by Sylar1982** [comment]
Hi,
i've tried to load that save2 but Valkyrie crashes as soon as i click on the save slot :|

**Comment by DelphiDie** [comment]
Sorry to hear that :( I fear I can't fix the issue in your current savegame then :(

Tantum fixed the bug in the campaign and the new release is already online.

Sadly the only workaround I can think of is starting a new campaign, and clicking through until you reach the finale again. Then just use the heroes with their abilities and items from your previous savegame.

I'm closing the issue, since the problem itself is fixed in the latest release.
