### ISSUE TITLE
Bug in Masquerade Ball I Encounter

### ISSUE THREAD

**Issue by AntonioFico** [DelphiDie/TheShadowRune#6]
The quest freeze during the SpawnOpenGroup2 event. If you delete the traitspool of Monster It functions.

Verify It please...the solution could affect others game dinamics.

Manu thanks

**Comment by DelphiDie** [comment]
Hello Antonio,

thanks for reporting the issue. I have a few questions about the problem:

Did the problem happen in encounter 1 or encounter 2 of the quest (both have a spawnopengroup2 event)?

Did you have any expansions activated in Valkyrie, or just the base game?

Is this problem reproduceable, or does it happen irregularly (there are known issue with spawning random monster groups in Valkyrie)?

Thanks and regards,
Delphi

**Comment by AntonioFico** [comment]
1) Did the problem happen in encounter 1 or encounter 2 of the quest (both have a spawnopengroup2 event)?

I had problem only in encounter I...the encounter II Is not affected.

2) Did you have any expansions activated in Valkyrie, or just the base game?

I activate and play, for now, only with the base game.

3) Is this problem reproduceable, or does it happen irregularly (there are known issue with spawning random monster groups in Valkyrie)?

I had not an answer because I don't have a good knowledge about Valkyrie and in my Digital conversion I use a manual selection system for open group. I'm Sorry, I can't help you with this.

**Comment by DelphiDie** [comment]
Thanks for your report, it helped a lot to nail down the issue. The problem happens, because the open group spawns are limited to the following traits: cursed building civilized.

With just the base game, there are only 3 monster groups, which fit these criteria:
Goblin Archers, Flesh Moulders and Zombies.

The spawn events however block Flesh Moulders and Goblin Archers, which means that the game will reliably run into the problem that it can't choose a group once the second open group should appear.

I'm not entirely sure why Goblin Archers are excluded from spawns (since I didn't create the quest), but I'll try to find out.

**Comment by DelphiDie** [comment]
After some digging, I found that goblin archers are excluded due to being used for another mechanic in the quest. As an easy fix I added the trait mountain to the allowed spawns. This will cause this quest to feature a different monsters than the original, but it is mostly in line with the theme. I'll upload a fixed version as soon as possible.

**Comment by DelphiDie** [comment]
The new bugfix release is live.
